from typing import Protocol

class FileLike(Protocol):
    def fileno(self) -> int: ...
    def readable(self) -> bool: ...
    def writable(self) -> bool: ...

def compress(data, level: int = 5, checksum: bool = False) -> bytes: ...
def decompress(data, original_size: int, checksum: bool = False) -> bytes: ...

def stream_compress(src: FileLike, dst: FileLike, 
                    n_threads: int = 0, level: int = 3, checksum: bool = False) -> None: ...

def stream_decompress(src: FileLike, dst: FileLike, 
                      n_threads: int = 0, checksum: bool = False) -> None: ...