def compress(data, level: int = 5, checksum: bool = False) -> bytes: ...
def decompress(data, checksum: bool = False) -> bytes: ...

def stream_compress(src, dst, n_threads: int = 0, level: int = 5, checksum: bool = False) -> None: ...
def stream_decompress(src, dst, n_threads: int = 0, checksum: bool = False) -> None: ...